approve_by_comment: true
approve_regex: '^(LGTM|lgtm|Approved|\+1|:\+1:)'
reject_regex: '^(Rejected|-1|:-1:)'
reset_on_push: true
reset_on_reopened: true
author_approval: ignored
reviewers:
  -
    name: default
    teams:
      - clear-containers-intel
    required: 2
    conditions:
      branches:
        - master
signed_off_by:
  required: true
